"""initial

Revision ID: 735322db506f
Revises: 4e5a2730289a
Create Date: 2023-07-09 15:46:29.777308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735322db506f'
down_revision = '4e5a2730289a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
